"""Public event types, channels, registries, and subscription helpers."""

from apixis.core.event.base import (
    EventType,
    ApixEvent,
    ApixEventError,
    EventHandlerFunc,
    EventHandlerErrorFunc,
    ApixEventHandler,
    ChannelType,
)
from apixis.core.event.event_loop import (
    APIX_EVENT_LOOP,
    ApixEventLoop,
)
from apixis.core.event.event_pipe import (
    EVENT_PIPE,
    ApixEventPipe,
    BaseEventChannel,
    ReadableEventChannel,
    WritableEventChannel,
    ReadWriteEventChannel,
    BuiltinChannel,
    GatewayChannel,
    KafkaChannel,
    RabbitMQChannel,
)
from apixis.core.utils.exception import (
    EventHandlerNotRegisteredError,
    EventHandlerAlreadyRegisteredError,
    EventChannelError,
    EventChannelPermissionError,
    EventChannelUnavailableError,
    GraphNodeError,
    InvalidNodeReturnsError,
    InvalidContextError,
)
from apixis.core.event.handler_registry import (
    ApixHandlerRegistry,
    APIX_HANDLER_REGISTRY,
    get_unmatched_subscriptions,
    subscribe,
    unsubscribe,
    get_handler,
    get_handler_meta,
    is_registered,
)
from apixis.core.event.event_registry import (
    ApixEventRegistry,
    APIX_EVENT_REGISTRY,
)

__all__ = [
    "EventType",
    "ApixEvent",
    "ApixEventError",
    "EventHandlerFunc",
    "EventHandlerErrorFunc",
    "ApixEventHandler",
    "ChannelType",
    "APIX_EVENT_LOOP",
    "ApixEventLoop",
    "EVENT_PIPE",
    "ApixEventPipe",
    "BaseEventChannel",
    "ReadableEventChannel",
    "WritableEventChannel",
    "ReadWriteEventChannel",
    "BuiltinChannel",
    "GatewayChannel",
    "KafkaChannel",
    "RabbitMQChannel",
    "EventHandlerNotRegisteredError",
    "EventHandlerAlreadyRegisteredError",
    "EventChannelError",
    "EventChannelPermissionError",
    "EventChannelUnavailableError",
    "GraphNodeError",
    "InvalidNodeReturnsError",
    "InvalidContextError",
    "ApixHandlerRegistry",
    "APIX_HANDLER_REGISTRY",
    "get_unmatched_subscriptions",
    "subscribe",
    "unsubscribe",
    "get_handler",
    "get_handler_meta",
    "is_registered",
    "ApixEventRegistry",
    "APIX_EVENT_REGISTRY",
]
